export default [
  { japanese: "わたし", english: "I (me)", kanji: "私" },
  { japanese: "わたしたち", english: "we", kanji: "" },
  { japanese: "あなた", english: "you", kanji: "" },
  { japanese: "あのかた", english: "that person (polite equivalent of あのひと [ あの人 ] )", kanji: "あの方" },
  { japanese: "みなさん", english: "everybody (ladies and gentlemen, all of you)", kanji: "皆さん" },
  { japanese: "にほん", english: "Japan (country)", kanji: "日本" },
  { japanese: "にほんじん", english: "Japanese nationality", kanji: "日本人" },
  { japanese: "せんせい", english: "teacher, instructor, medical doctor (not used when referring to one&#x27;s own job)", kanji: "先生" },
  { japanese: "きょうし", english: "teacher, instructor", kanji: "教師" },
  { japanese: "がくせい", english: "student", kanji: "学生" },
  { japanese: "かいしゃいん", english: "company employee", kanji: "会社員" },
  { japanese: "ぎんこういん", english: "bank employee", kanji: "銀行員" },
  { japanese: "いしゃ", english: "medical doctor", kanji: "医者" },
  { japanese: "けんきゅうしゃ", english: "researcher, scholar", kanji: "研究者" },
  { japanese: "エンジニア", english: "engineer", kanji: "" },
  { japanese: "だいがく", english: "university", kanji: "大学" },
  { japanese: "びょういん", english: "hospital", kanji: "病院" },
  { japanese: "でんき", english: "electricity, light", kanji: "電気" },
  { japanese: "どなた", english: "who (polite equivalent of だれ)", kanji: "" },
  { japanese: "おいくつ", english: "how old (polite equivalent of なんさい [ 何歳 ] )", kanji: "" },
  { japanese: "はい", english: "yes (alternative: ええ)", kanji: "" },
  { japanese: "いいえ", english: "no", kanji: "" },
  { japanese: "なまえは なんですか", english: "What is your name?", kanji: "" },
  { japanese: "はじめまして", english: "How do you do? (usually used as the first phrase when introducing oneself)", kanji: "" },
  { japanese: "どうぞ よろしく", english: "Pleased to meet you (usually used at the end of a self-introduction)", kanji: "" },
  { japanese: "これ", english: "this (thing close to speaker)", kanji: "" },
  { japanese: "それ", english: "that (thing distant from speaker, close to listener)", kanji: "" },
  { japanese: "あれ", english: "that (thing distant from both speaker and listener)", kanji: "" },
  { japanese: "ほん", english: "book", kanji: "本" },
  { japanese: "じしょ", english: "dictionary", kanji: "辞書" },
  { japanese: "ざっし", english: "magazine", kanji: "雑誌" },
  { japanese: "しんぶん", english: "newspaper", kanji: "新聞" },
  { japanese: "ノート", english: "notebook", kanji: "" },
  { japanese: "てちょう", english: "pocket notebook", kanji: "手帳" },
  { japanese: "めいし", english: "business card", kanji: "名刺" },
  { japanese: "カード", english: "card", kanji: "" },
  { japanese: "テレホンカード", english: "telephone card", kanji: "" },
  { japanese: "えんぴつ", english: "pencil", kanji: "鉛筆" },
  { japanese: "ボールペン", english: "ballpoint pen", kanji: "" },
  { japanese: "シャープペンシル", english: "mechanical pencil, propelling pencil", kanji: "" },
  { japanese: "かぎ", english: "key(s)", kanji: "" },
  { japanese: "とけい", english: "watch, clock", kanji: "時計" },
  { japanese: "かさ", english: "umbrella", kanji: "傘" },
  { japanese: "かばん", english: "handbag, briefcase", kanji: "" },
  { japanese: "カセットテープ", english: "cassette tape", kanji: "" },
  { japanese: "テレビ", english: "television", kanji: "" },
  { japanese: "ラジオ", english: "radio", kanji: "" },
  { japanese: "カメラ", english: "camera", kanji: "" },
  { japanese: "コンピューター", english: "computer", kanji: "" },
  { japanese: "じどうしゃ", english: "automobile", kanji: "自動車" },
  { japanese: "つくえ", english: "desk", kanji: "机" },
  { japanese: "いす", english: "chair", kanji: "" },
  { japanese: "チョコレート", english: "chocolate", kanji: "" },
  { japanese: "コーヒー", english: "coffee", kanji: "" },
  { japanese: "えいご", english: "English language", kanji: "英語" },
  { japanese: "にほんご", english: "Japanese language", kanji: "日本語" },
  { japanese: "なに", english: "what", kanji: "何" },
  { japanese: "そう", english: "so", kanji: "" },
  { japanese: "ちがいます", english: "it isn’t (you are wrong)", kanji: "違います" },
  { japanese: "そうですか", english: "I see/understand (is that so?)", kanji: "" },
  { japanese: "あのう", english: "well (used to show hesitation)", kanji: "" },
  { japanese: "どうぞ", english: "here you are (used when offering someone something)", kanji: "" },
  { japanese: "どうも", english: "well, thanks", kanji: "" },
  { japanese: "ありがとう", english: "thank you", kanji: "" },
  { japanese: "ここ", english: "here (this place)", kanji: "" },
  { japanese: "そこ", english: "there (that place near listener)", kanji: "" },
  { japanese: "あそこ", english: "over there (place distant from speaker and listener)", kanji: "" },
  { japanese: "どこ", english: "where", kanji: "" },
  { japanese: "こちら", english: "this way (direction close or towards speaker)", kanji: "" },
  { japanese: "そちら", english: "that way (direction distant from speaker, close to listener)", kanji: "" },
  { japanese: "あちら", english: "that way (direction distant from speaker and listener)", kanji: "" },
  { japanese: "きょうしつ", english: "classroom", kanji: "教室" },
  { japanese: "しょくどう", english: "dining hall, canteen", kanji: "食堂" },
  { japanese: "じむしょ", english: "office", kanji: "事務所" },
  { japanese: "かいぎしつ", english: "conference room", kanji: "会議室" },
  { japanese: "うけつけ", english: "reception desk", kanji: "受付" },
  { japanese: "ロビー", english: "lobby", kanji: "" },
  { japanese: "へや", english: "room", kanji: "部屋" },
  { japanese: "おてあらい", english: "toilet, restroom (alternative: トイレ)", kanji: "お手洗い" },
  { japanese: "かいだん", english: "staircase", kanji: "階段" },
  { japanese: "エレベーター", english: "elevator", kanji: "" },
  { japanese: "エスカレーター", english: "escalator", kanji: "" },
  { japanese: "くに", english: "country", kanji: "国" },
  { japanese: "かいしゃ", english: "company", kanji: "会社" },
  { japanese: "うち", english: "house, home", kanji: "" },
  { japanese: "でんわ", english: "telephone, telephone call", kanji: "電話" },
  { japanese: "くつ", english: "shoes", kanji: "靴" },
  { japanese: "ネクタイ", english: "necktie", kanji: "" },
  { japanese: "ワイン", english: "wine", kanji: "" },
  { japanese: "たばこ", english: "tobacco, cigarette", kanji: "" },
  { japanese: "うりば", english: "place where things are sold (department, counter in department store)", kanji: "売り場" },
  { japanese: "ちか", english: "basement", kanji: "地下" },
  { japanese: "なんがい", english: "which floor", kanji: "何階" },
  { japanese: "いくら", english: "how much", kanji: "" },
  { japanese: "ひゃく", english: "hundred", kanji: "百" },
  { japanese: "せん", english: "thousand", kanji: "千" },
  { japanese: "まん", english: "ten thousand", kanji: "万" },
  { japanese: "すみません", english: "excuse me, I am sorry", kanji: "" },
  { japanese: "おきます", english: "to put, to place", kanji: "置きます" },
  { japanese: "ねます", english: "to sleep, to go to bed", kanji: "寝ます" },
  { japanese: "はたらきます", english: "to work", kanji: "働きます" },
  { japanese: "やすみます", english: "to rest, take a break", kanji: "休みます" },
  { japanese: "べんきょうします", english: "to study", kanji: "勉強します" },
  { japanese: "おわります", english: "to finish", kanji: "終わります" },
  { japanese: "デパート", english: "department store", kanji: "" },
  { japanese: "ぎんこう", english: "bank", kanji: "銀行" },
  { japanese: "ゆうびんきょく", english: "post office", kanji: "郵便局" },
  { japanese: "としょかん", english: "library", kanji: "図書館" },
  { japanese: "びじゅつかん", english: "art museum", kanji: "美術館" },
  { japanese: "いま", english: "now", kanji: "今" },
  { japanese: "なんじ", english: "what time", kanji: "何時" },
  { japanese: "ごぜん", english: "a.m., morning (used when telling time)", kanji: "午前" },
  { japanese: "ごご", english: "p.m., afternoon (used when telling time)", kanji: "午後" },
  { japanese: "あさ", english: "morning", kanji: "朝" },
  { japanese: "ひる", english: "noon", kanji: "昼" },
  { japanese: "よる", english: "night", kanji: "夜" },
  { japanese: "ばん", english: "evening", kanji: "晩" },
  { japanese: "おととい", english: "the day before yesterday", kanji: "" },
  { japanese: "きのう", english: "yesterday", kanji: "" },
  { japanese: "きょう", english: "today", kanji: "" },
  { japanese: "あした", english: "tomorrow", kanji: "" },
  { japanese: "あさって", english: "day after tomorrow", kanji: "" },
  { japanese: "けさ", english: "this morning", kanji: "" },
  { japanese: "こんばん", english: "this evening, tonight", kanji: "今晩" },
  { japanese: "やすみ", english: "rest, a holiday, a day off", kanji: "休み" },
  { japanese: "ひるやすみ", english: "lunchtime, lunch break", kanji: "昼休み" },
  { japanese: "まいあさ", english: "every morning", kanji: "毎朝" },
  { japanese: "まいにち", english: "every day", kanji: "毎日" },
  { japanese: "げつようび", english: "Monday", kanji: "月曜日" },
  { japanese: "かようび", english: "Tuesday", kanji: "火曜日" },
  { japanese: "すいようび", english: "Wednesday", kanji: "水曜日" },
  { japanese: "もくようび", english: "Thursday", kanji: "木曜日" },
  { japanese: "きんようび", english: "Friday", kanji: "金曜日" },
  { japanese: "どようび", english: "Saturday", kanji: "土曜日" },
  { japanese: "にちようび", english: "Sunday", kanji: "日曜日" },
  { japanese: "なんようび", english: "what day of the week", kanji: "何曜日" },
  { japanese: "ばんごう", english: "number (sequence)", kanji: "番号" },
  { japanese: "たいへんですね", english: "rough/tough (difficult), isn’t it? (used when expressing sympathy)", kanji: "大変ですね" },
  { japanese: "いきます", english: "to go", kanji: "行きます" },
  { japanese: "きます", english: "to put on, to wear (shirts, etc. [upper body] )", kanji: "着ます" },
  { japanese: "かえります", english: "to go home, to return", kanji: "帰ります" },
  { japanese: "がっこう", english: "school", kanji: "学校" },
  { japanese: "スーパー", english: "supermarket", kanji: "" },
  { japanese: "えき", english: "station", kanji: "駅" },
  { japanese: "ひこうき", english: "airplane", kanji: "飛行機" },
  { japanese: "ふね", english: "ship", kanji: "船" },
  { japanese: "でんしゃ", english: "train", kanji: "電車" },
  { japanese: "ちかてつ", english: "subway, underground", kanji: "地下鉄" },
  { japanese: "しんかんせん", english: "Shinkansen, the Japanese bullet train", kanji: "" },
  { japanese: "バス", english: "bus", kanji: "" },
  { japanese: "タクシー", english: "taxi", kanji: "" },
  { japanese: "じてんしゃ", english: "bicycle", kanji: "自転車" },
  { japanese: "あるいて", english: "on foot", kanji: "歩いて" },
  { japanese: "ひと", english: "person", kanji: "人" },
  { japanese: "ときどき", english: "sometimes", kanji: "時々" },
  { japanese: "ともだち", english: "friend", kanji: "友達" },
  { japanese: "かれ", english: "he, boyfriend", kanji: "彼" },
  { japanese: "かのじょ", english: "she, girlfriend", kanji: "彼女" },
  { japanese: "かぞく", english: "family", kanji: "家族" },
  { japanese: "せんしゅう", english: "last week", kanji: "先週" },
  { japanese: "こんしゅう", english: "this week", kanji: "今週" },
  { japanese: "らいしゅう", english: "next week", kanji: "来週" },
  { japanese: "せんげつ", english: "last month", kanji: "先月" },
  { japanese: "こんげつ", english: "this month", kanji: "今月" },
  { japanese: "らいげつ", english: "next month", kanji: "来月" },
  { japanese: "きょねん", english: "last year", kanji: "去年" },
  { japanese: "ことし", english: "this year", kanji: "" },
  { japanese: "らいねん", english: "next year", kanji: "来年" },
  { japanese: "なんがつ", english: "what month", kanji: "何月" },
  { japanese: "ついたち", english: "first day of the month", kanji: "1日" },
  { japanese: "ふつか", english: "second day of the month", kanji: "" },
  { japanese: "みっか", english: "third day of the month", kanji: "" },
  { japanese: "よっか", english: "fourth day of the month", kanji: "" },
  { japanese: "いつか", english: "fifth day of the month", kanji: "" },
  { japanese: "むいか", english: "sixth day of the month", kanji: "6日" },
  { japanese: "なのか", english: "seventh day of the month", kanji: "" },
  { japanese: "ようか", english: "eighth day of the month", kanji: "" },
  { japanese: "ここのか", english: "ninth day of the month", kanji: "" },
  { japanese: "とおか", english: "tenth day of the month", kanji: "10日" },
  { japanese: "じゅういちにち", english: "eleventh day of the month", kanji: "" },
  { japanese: "じゅうににち", english: "twelfth day of the month", kanji: "" },
  { japanese: "じゅうさんにち", english: "thirteenth day of the month", kanji: "" },
  { japanese: "じゅうよっか", english: "fourteenth day of the month", kanji: "14日" },
  { japanese: "はつか", english: "twentieth day of the month", kanji: "20日" },
  { japanese: "にじゅうごにち", english: "twenty-fifth day of the month", kanji: "" },
  { japanese: "さんじゅうにち", english: "thirtieth day of the month", kanji: "" },
  { japanese: "なんにち", english: "which day of the month", kanji: "何日" },
  { japanese: "いつ", english: "when", kanji: "" },
  { japanese: "たんじょうび", english: "birthday", kanji: "誕生日" },
  { japanese: "ふつう", english: "local (train)", kanji: "普通" },
  { japanese: "きゅうこう", english: "rapid (train)", kanji: "急行" },
  { japanese: "とっきゅう", english: "express (train), can also be translated as “limited express”", kanji: "特急" },
  { japanese: "つぎの", english: "next (something)", kanji: "次の" },
  { japanese: "たべます", english: "to eat", kanji: "食べます" },
  { japanese: "のみます", english: "to drink", kanji: "飲みます" },
  { japanese: "すいます", english: "to smoke (a cigarette)", kanji: "吸います" },
  { japanese: "みます", english: "to see, to watch", kanji: "見ます" },
  { japanese: "ききます", english: "to hear, to listen, to ask", kanji: "聞きます" },
  { japanese: "よみます", english: "to read", kanji: "読みます" },
  { japanese: "かきます", english: "to write, to draw", kanji: "書きます" },
  { japanese: "かいます", english: "to buy", kanji: "買います" },
  { japanese: "とります", english: "to take (a photograph), to record (audio, video)", kanji: "撮ります" },
  { japanese: "します", english: "to do", kanji: "" },
  { japanese: "ともだちにあいます", english: "to meet a friend", kanji: "友達に会います" },
  { japanese: "ごはん", english: "a meal, cooked rice", kanji: "" },
  { japanese: "あさごはん", english: "breakfast", kanji: "朝ごはん" },
  { japanese: "ひるごはん", english: "lunch", kanji: "昼ごはん" },
  { japanese: "ばんごはん", english: "supper", kanji: "晩ごはん" },
  { japanese: "パン", english: "bread", kanji: "" },
  { japanese: "たまご", english: "egg(s)", kanji: "卵" },
  { japanese: "にく", english: "meat", kanji: "肉" },
  { japanese: "さかな", english: "fish", kanji: "魚" },
  { japanese: "やさい", english: "vegetable", kanji: "野菜" },
  { japanese: "くだもの", english: "fruit", kanji: "果物" },
  { japanese: "みず", english: "water", kanji: "水" },
  { japanese: "おちゃ", english: "tea (usually green tea)", kanji: "お茶" },
  { japanese: "こうちゃ", english: "black tea", kanji: "紅茶" },
  { japanese: "ぎゅうにゅう", english: "milk (alternative: ミルク)", kanji: "牛乳" },
  { japanese: "ジュース", english: "juice", kanji: "" },
  { japanese: "ビール", english: "beer", kanji: "" },
  { japanese: "さけ", english: "sake (Japanese rice wine)", kanji: "酒" },
  { japanese: "ビデオ", english: "video tape", kanji: "" },
  { japanese: "えいが", english: "movie", kanji: "映画" },
  { japanese: "てがみ", english: "letter", kanji: "手紙" },
  { japanese: "レポート", english: "report", kanji: "" },
  { japanese: "しゃしん", english: "photograph", kanji: "写真" },
  { japanese: "みせ", english: "shop, store", kanji: "店" },
  { japanese: "レストラン", english: "restaurant (especially Western-style)", kanji: "" },
  { japanese: "にわ", english: "garden", kanji: "庭" },
  { japanese: "しゅくだい", english: "homework", kanji: "宿題" },
  { japanese: "テニス", english: "tennis", kanji: "" },
  { japanese: "サッカー", english: "soccer, football", kanji: "" },
  { japanese: "はなみ", english: "cherry-blossom viewing", kanji: "花見" },
  { japanese: "いっしょに", english: "together", kanji: "" },
  { japanese: "ちょっと", english: "a little while, a little bit (can be used informally as: “one moment please”)", kanji: "" },
  { japanese: "いつも", english: "always", kanji: "" },
  { japanese: "それから", english: "after that, and then, therefor", kanji: "" },
  { japanese: "いいですね", english: "that’s good (it’s alright?)", kanji: "" },
  { japanese: "わかりました", english: "I understand", kanji: "" },
  { japanese: "また", english: "again (can also be used as &quot;see you later/see you some other time&quot;)", kanji: "" },
  { japanese: "きります", english: "to cut, to slice", kanji: "切ります" },
  { japanese: "おくります", english: "to escort/to go with (someone), to see off (a person), to bid farewell", kanji: "送ります" },
  { japanese: "あげます", english: "to give", kanji: "" },
  { japanese: "もらいます", english: "to receive", kanji: "" },
  { japanese: "かします", english: "to lend", kanji: "貸します" },
  { japanese: "かります", english: "to borrow", kanji: "借ります" },
  { japanese: "おしえます", english: "to teach, to tell, to inform", kanji: "教えます" },
  { japanese: "ならいます", english: "to learn", kanji: "習います" },
  { japanese: "でんわをかけます", english: "to make a telephone call", kanji: "電話をかけます" },
  { japanese: "て", english: "hand", kanji: "手" },
  { japanese: "はし", english: "bridge", kanji: "橋" },
  { japanese: "スプーン", english: "spoon", kanji: "" },
  { japanese: "ナイフ", english: "knife", kanji: "" },
  { japanese: "フォーク", english: "fork", kanji: "" },
  { japanese: "はさみ", english: "scissors", kanji: "" },
  { japanese: "ファクス", english: "fax", kanji: "" },
  { japanese: "ワープロ", english: "word processor", kanji: "" },
  { japanese: "パソコン", english: "personal computer", kanji: "" },
  { japanese: "ホッチキス", english: "stapler", kanji: "" },
  { japanese: "セロテープ", english: "clear tape", kanji: "" },
  { japanese: "けしゴム", english: "eraser", kanji: "消しゴム" },
  { japanese: "かみ", english: "hair", kanji: "髪" },
  { japanese: "はな", english: "flower", kanji: "花" },
  { japanese: "シャツ", english: "shirt", kanji: "" },
  { japanese: "プレゼント", english: "present", kanji: "" },
  { japanese: "にもつ", english: "baggage", kanji: "荷物" },
  { japanese: "おかね", english: "money", kanji: "お金" },
  { japanese: "きっぷ", english: "ticket", kanji: "切符" },
  { japanese: "クリスマス", english: "Christmas", kanji: "" },
  { japanese: "ちち", english: "(my) father", kanji: "父" },
  { japanese: "はは", english: "(my) mother", kanji: "母" },
  { japanese: "おとうさん", english: "(someone else’s) father", kanji: "お父さん" },
  { japanese: "おかあさん", english: "(someone else’s) mother", kanji: "お母さん" },
  { japanese: "もう", english: "already, again", kanji: "" },
  { japanese: "まだ", english: "not yet", kanji: "" },
  { japanese: "これから", english: "from now on, soon", kanji: "" },
  { japanese: "ごめんください", english: "may I come in? (anybody home?)", kanji: "" },
  { japanese: "いらっしゃい", english: "welcome (nice of you to come)", kanji: "" },
  { japanese: "いただきます", english: "thank you/I accept (used before starting to eat or drink)", kanji: "" },
  { japanese: "りょこう", english: "trip, travel", kanji: "旅行" },
  { japanese: "おみやげ", english: "souvenir", kanji: "お土産" },
  { japanese: "ヨーロッパ", english: "Europe", kanji: "" },
  { japanese: "ハンサム", english: "handsome", kanji: "" },
  { japanese: "きれい", english: "beautiful, clean", kanji: "" },
  { japanese: "しずか", english: "quiet", kanji: "静か" },
  { japanese: "にぎやか", english: "lively", kanji: "" },
  { japanese: "ゆうめい", english: "famous", kanji: "有名" },
  { japanese: "しんせつ", english: "kind", kanji: "親切" },
  { japanese: "げんき", english: "healthy, cheerful, energetic", kanji: "元気" },
  { japanese: "ひま", english: "free (time)", kanji: "暇" },
  { japanese: "べんり", english: "convenient, handy", kanji: "便利" },
  { japanese: "すてき", english: "nice, wonderful", kanji: "" },
  { japanese: "おおきい", english: "big", kanji: "大きい" },
  { japanese: "ちいさい", english: "small", kanji: "小さい" },
  { japanese: "あたらしい", english: "new", kanji: "新しい" },
  { japanese: "ふるい", english: "old (not of age)", kanji: "古い" },
  { japanese: "いい", english: "good", kanji: "" },
  { japanese: "わるい", english: "bad", kanji: "悪い" },
  { japanese: "あつい", english: "hot (referring to temperature [e.g. weather] or touch/objects)", kanji: "暑い or 熱い" },
  { japanese: "さむい", english: "cold (referring to temperature, e.g. weather)", kanji: "寒い" },
  { japanese: "つめたい", english: "cold (referring to touch/objects)", kanji: "冷たい" },
  { japanese: "むずかしい", english: "difficult", kanji: "難しい" },
  { japanese: "やさしい", english: "easy", kanji: "易しい" },
  { japanese: "たかい", english: "expensive, high", kanji: "高い" },
  { japanese: "やすい", english: "inexpensive", kanji: "安い" },
  { japanese: "ひくい", english: "low", kanji: "低い" },
  { japanese: "おもしろい", english: "interesting", kanji: "" },
  { japanese: "おいしい", english: "delicious, tasty", kanji: "" },
  { japanese: "いそがしい", english: "busy (referring to activity)", kanji: "忙しい" },
  { japanese: "たのしい", english: "enjoyable", kanji: "楽しい" },
  { japanese: "しろい", english: "white", kanji: "白い" },
  { japanese: "くろい", english: "black", kanji: "黒い" },
  { japanese: "あかい", english: "red", kanji: "赤い" },
  { japanese: "あおい", english: "blue", kanji: "青い" },
  { japanese: "さくら", english: "Sakura (cherry blossom)", kanji: "桜" },
  { japanese: "やま", english: "mountain", kanji: "山" },
  { japanese: "まち", english: "town, city", kanji: "町" },
  { japanese: "たべもの", english: "food", kanji: "食べ物" },
  { japanese: "くるま", english: "vehicle, car", kanji: "車" },
  { japanese: "ところ", english: "place", kanji: "所" },
  { japanese: "りょう", english: "dormitory", kanji: "寮" },
  { japanese: "べんきょう", english: "study", kanji: "勉強" },
  { japanese: "せいかつ", english: "life", kanji: "生活" },
  { japanese: "しごと", english: "work, business", kanji: "仕事" },
  { japanese: "どう", english: "how", kanji: "" },
  { japanese: "どれ", english: "which one (of three or more)", kanji: "" },
  { japanese: "とても", english: "very", kanji: "" },
  { japanese: "あまり", english: "not so (used with negatives)", kanji: "" },
  { japanese: "そして", english: "and (used to connect sentences)", kanji: "" },
  { japanese: "おげんきですか", english: "how are you?", kanji: "お元気ですか" },
  { japanese: "そうですね", english: "well let me see (is that so?) (can also be used as &quot;I agree with you&quot;)", kanji: "" },
  { japanese: "わかります", english: "to understand", kanji: "" },
  { japanese: "すき", english: "like", kanji: "好き" },
  { japanese: "きらい", english: "dislike", kanji: "嫌い" },
  { japanese: "じょうず", english: "good at", kanji: "上手" },
  { japanese: "へた", english: "poor at", kanji: "下手" },
  { japanese: "りょうり", english: "dish (cooked food)", kanji: "料理" },
  { japanese: "のみもの", english: "drinks", kanji: "飲み物" },
  { japanese: "スポーツ", english: "sports", kanji: "" },
  { japanese: "やきゅう", english: "baseball", kanji: "野球" },
  { japanese: "ダンス", english: "dance", kanji: "" },
  { japanese: "おんがく", english: "music", kanji: "音楽" },
  { japanese: "うた", english: "song", kanji: "歌" },
  { japanese: "クラシック", english: "classical music", kanji: "" },
  { japanese: "ジャズ", english: "jazz", kanji: "" },
  { japanese: "コンサート", english: "concert", kanji: "" },
  { japanese: "カラオケ", english: "karaoke", kanji: "" },
  { japanese: "かぶき", english: "Kabuki (traditional Japanese musical drama)", kanji: "歌舞伎" },
  { japanese: "え", english: "picture, drawing", kanji: "絵" },
  { japanese: "じ", english: "letter, character", kanji: "字" },
  { japanese: "かんじ", english: "Kanji, Chinese character", kanji: "漢字" },
  { japanese: "ひらがな", english: "Hiragana script", kanji: "" },
  { japanese: "かたかな", english: "Katakana script", kanji: "" },
  { japanese: "ローマじ", english: "Roman alphabet", kanji: "ローマ字" },
  { japanese: "じかん", english: "time", kanji: "時間" },
  { japanese: "ようじ", english: "something to do, errand", kanji: "用事" },
  { japanese: "やくそく", english: "promise", kanji: "約束" },
  { japanese: "ごしゅじん", english: "(someone else’s) husband", kanji: "ご主人" },
  { japanese: "おっと", english: "(my) husband (alternative: しゅじん [ 主人 ] )", kanji: "夫" },
  { japanese: "おくさん", english: "(someone else’s) wife", kanji: "奥さん" },
  { japanese: "つま", english: "(my) wife (alternative: かない [ 家内 ] )", kanji: "妻" },
  { japanese: "こども", english: "child", kanji: "子ども" },
  { japanese: "よく", english: "often", kanji: "" },
  { japanese: "だいたい", english: "mostly, roughly", kanji: "" },
  { japanese: "たくさん", english: "many, much", kanji: "" },
  { japanese: "すこし", english: "a little, a few", kanji: "少し" },
  { japanese: "ぜんぜん", english: "not at all (used with negatives)", kanji: "全然" },
  { japanese: "はやく", english: "quickly, fast", kanji: "早く or 速く" },
  { japanese: "どうして", english: "why", kanji: "" },
  { japanese: "ざんねんです", english: "that’s a pity (I’m sorry to hear that)", kanji: "残念です" },
  { japanese: "もしもし", english: "hello (used on the phone)", kanji: "" },
  { japanese: "ああ", english: "oh", kanji: "" },
  { japanese: "います", english: "to have, to exist (referring to animate/alive things)", kanji: "" },
  { japanese: "あります", english: "to have, to exist (referring to inanimate/lifeless things)", kanji: "" },
  { japanese: "いろいろ", english: "various", kanji: "" },
  { japanese: "おとこのひと", english: "man", kanji: "男の人" },
  { japanese: "おんなのひと", english: "woman", kanji: "女の人" },
  { japanese: "おとこのこ", english: "boy", kanji: "男の子" },
  { japanese: "おんなのこ", english: "girl", kanji: "女の子" },
  { japanese: "いぬ", english: "dog", kanji: "犬" },
  { japanese: "ねこ", english: "cat", kanji: "猫" },
  { japanese: "き", english: "tree", kanji: "木" },
  { japanese: "もの", english: "thing", kanji: "物" },
  { japanese: "でんち", english: "battery", kanji: "電池" },
  { japanese: "はこ", english: "box", kanji: "箱" },
  { japanese: "スイッチ", english: "switch", kanji: "" },
  { japanese: "れいぞうこ", english: "refrigerator", kanji: "冷蔵庫" },
  { japanese: "テーブル", english: "table", kanji: "" },
  { japanese: "ベッド", english: "bed", kanji: "" },
  { japanese: "たな", english: "shelf", kanji: "棚" },
  { japanese: "ドア", english: "door (Western-style)", kanji: "" },
  { japanese: "まど", english: "window", kanji: "窓" },
  { japanese: "ポスト", english: "mailbox, post box", kanji: "" },
  { japanese: "こうえん", english: "park", kanji: "公園" },
  { japanese: "きっさてん", english: "coffee shop", kanji: "喫茶店" },
  { japanese: "ほんや", english: "bookstore", kanji: "本屋" },
  { japanese: "のりば", english: "fixed place to catch taxis, trains, etc. (e.g. a platform)", kanji: "乗り場" },
  { japanese: "けん", english: "prefecture", kanji: "県" },
  { japanese: "うえ", english: "above, over, on top", kanji: "上" },
  { japanese: "した", english: "under, below", kanji: "下" },
  { japanese: "まえ", english: "in front, before", kanji: "前" },
  { japanese: "うしろ", english: "back, behind", kanji: "" },
  { japanese: "みぎ", english: "right (side)", kanji: "右" },
  { japanese: "ひだり", english: "left (side)", kanji: "左" },
  { japanese: "なか", english: "in, inside", kanji: "中" },
  { japanese: "そと", english: "outside", kanji: "外" },
  { japanese: "となり", english: "next to, next door, neighbour", kanji: "隣" },
  { japanese: "ちかく", english: "near, vicinity", kanji: "近く" },
  { japanese: "あいだ", english: "between, among", kanji: "間" },
  { japanese: "かかります", english: "to take (referring to time or money)", kanji: "" },
  { japanese: "ひとつ", english: "one (thing)", kanji: "1つ" },
  { japanese: "ふたつ", english: "two (things)", kanji: "2つ" },
  { japanese: "みっつ", english: "three (things)", kanji: "3つ" },
  { japanese: "よっつ", english: "four (things)", kanji: "4つ" },
  { japanese: "いつつ", english: "five (things)", kanji: "5つ" },
  { japanese: "むっつ", english: "six (things)", kanji: "6つ" },
  { japanese: "ななつ", english: "seven (things)", kanji: "7つ" },
  { japanese: "やっつ", english: "eight (things)", kanji: "8つ" },
  { japanese: "ここのつ", english: "nine (things)", kanji: "9つ" },
  { japanese: "とお", english: "ten (things)", kanji: "" },
  { japanese: "いくつ", english: "how many things", kanji: "" },
  { japanese: "ひとり「で」", english: "one person, alone, by oneself", kanji: "1人「で」" },
  { japanese: "ふたり", english: "two persons", kanji: "2人" },
  { japanese: "さんにん", english: "three persons (counter ~にん for three or more people)", kanji: "3人" },
  { japanese: "よにん", english: "four persons", kanji: "4人" },
  { japanese: "なんにん", english: "how many people", kanji: "何人" },
  { japanese: "りんご", english: "apple", kanji: "" },
  { japanese: "みかん", english: "mandarin orange", kanji: "" },
  { japanese: "サンドイッチ", english: "sandwich", kanji: "" },
  { japanese: "カレーライス", english: "curry and rice", kanji: "" },
  { japanese: "アイスクリーム", english: "ice cream", kanji: "" },
  { japanese: "きって", english: "postage stamp", kanji: "切手" },
  { japanese: "はがき", english: "postcard", kanji: "" },
  { japanese: "ふうとう", english: "envelope", kanji: "封筒" },
  { japanese: "そくたつ", english: "express mail", kanji: "速達" },
  { japanese: "かきとめ", english: "registered mail", kanji: "書留" },
  { japanese: "こうくうびん", english: "airmail (alternative: エアメール)", kanji: "航空便" },
  { japanese: "ふなびん", english: "sea mail", kanji: "船便" },
  { japanese: "りょうしん", english: "parents", kanji: "両親" },
  { japanese: "きょうだい", english: "brothers and sisters", kanji: "兄弟" },
  { japanese: "あに", english: "(my) elder brother", kanji: "兄" },
  { japanese: "おにいさん", english: "(someone else’s) elder brother", kanji: "お兄さん" },
  { japanese: "あね", english: "(my) elder sister", kanji: "姉" },
  { japanese: "おねえさん", english: "(someone else’s) elder sister", kanji: "お姉さん" },
  { japanese: "おとうと", english: "(my) younger brother", kanji: "弟" },
  { japanese: "おとうとさん", english: "(someone else’s) younger brother", kanji: "弟さん" },
  { japanese: "いもうと", english: "(my) younger sister", kanji: "妹" },
  { japanese: "いもうとさん", english: "(someone else’s) younger sister", kanji: "妹さん" },
  { japanese: "がいこく", english: "foreign country", kanji: "外国" },
  { japanese: "どのくらい", english: "how long", kanji: "" },
  { japanese: "ぜんぶ「で」", english: "all, everything, in total", kanji: "全部「で」" },
  { japanese: "かんたん", english: "simple", kanji: "簡単" },
  { japanese: "ちかい", english: "near", kanji: "近い" },
  { japanese: "とおい", english: "distant, far", kanji: "遠い" },
  { japanese: "はやい", english: "fast, early", kanji: "速い or 早い" },
  { japanese: "おそい", english: "slow, late", kanji: "遅い" },
  { japanese: "ひとがおおい", english: "many people", kanji: "人が多い" },
  { japanese: "ひとがすくない", english: "few people", kanji: "人が少ない" },
  { japanese: "あたたかい", english: "warm (referring to temperature [e.g. weather] or touch/objects)", kanji: "暖かい or 温かい" },
  { japanese: "すずしい", english: "pleasantly cool (referring to temperature [e.g. weather] or touch/objects)", kanji: "涼しい" },
  { japanese: "あまい", english: "sweet", kanji: "甘い" },
  { japanese: "からい", english: "spicy, hot taste", kanji: "辛い" },
  { japanese: "おもい", english: "heavy", kanji: "重い" },
  { japanese: "かるい", english: "light (opposite of heavy)", kanji: "軽い" },
  { japanese: "きせつ", english: "season", kanji: "季節" },
  { japanese: "はる", english: "spring (season)", kanji: "春" },
  { japanese: "なつ", english: "summer", kanji: "夏" },
  { japanese: "あき", english: "autumn", kanji: "秋" },
  { japanese: "ふゆ", english: "winter", kanji: "冬" },
  { japanese: "てんき", english: "weather", kanji: "天気" },
  { japanese: "あめ", english: "rain, rainy", kanji: "雨" },
  { japanese: "ゆき", english: "snow, snowy", kanji: "雪" },
  { japanese: "くもり", english: "cloudy", kanji: "曇り" },
  { japanese: "ホテル", english: "hotel", kanji: "" },
  { japanese: "くうこう", english: "airport", kanji: "空港" },
  { japanese: "うみ", english: "sea, ocean", kanji: "海" },
  { japanese: "せかい", english: "world", kanji: "世界" },
  { japanese: "パーティー", english: "party", kanji: "" },
  { japanese: "まつり", english: "festival", kanji: "祭り" },
  { japanese: "しけん", english: "examination, test", kanji: "試験" },
  { japanese: "すきやき", english: "sukiyaki (beef and vegetable hot pot)", kanji: "すき焼き" },
  { japanese: "さしみ", english: "sashimi (sliced raw fish)", kanji: "刺身" },
  { japanese: "すし", english: "sushi (vinegared rice topped with raw fish)", kanji: "" },
  { japanese: "てんぷら", english: "tempura (seafood and vegetable deep fried in batter)", kanji: "" },
  { japanese: "いけばな", english: "flower arrangement", kanji: "生け花" },
  { japanese: "もみじ", english: "maple, red leaves of autumn", kanji: "紅葉" },
  { japanese: "どちら", english: "which one (between two things)", kanji: "" },
  { japanese: "どちらも", english: "both", kanji: "" },
  { japanese: "ずっと", english: "throughout, by far", kanji: "" },
  { japanese: "はじめて", english: "for the first time", kanji: "初めて" },
  { japanese: "ただいま", english: "I’m home", kanji: "" },
  { japanese: "おかえりなさい", english: "welcome home", kanji: "お帰りなさい" },
  { japanese: "すごいですね", english: "that’s amazing (~isn’t it?)", kanji: "" },
  { japanese: "でも", english: "but", kanji: "" },
  { japanese: "つかれました", english: "(I’m) tired", kanji: "疲れました" },
  { japanese: "あそびます", english: "to enjoy oneself, to play", kanji: "遊びます" },
  { japanese: "およぎます", english: "to swim", kanji: "泳ぎます" },
  { japanese: "むかえます", english: "to go to meet, to welcome", kanji: "迎えます" },
  { japanese: "つかれます", english: "to get tired", kanji: "疲れます" },
  { japanese: "てがみをだします", english: "to send a letter", kanji: "手紙を出します" },
  { japanese: "はいります", english: "to enter", kanji: "入ります" },
  { japanese: "でます", english: "to exit, to go out", kanji: "出ます" },
  { japanese: "けっこんします", english: "to marry", kanji: "結婚します" },
  { japanese: "かいものします", english: "to shop", kanji: "買い物します" },
  { japanese: "しょくじします", english: "to dine", kanji: "食事します" },
  { japanese: "さんぽします", english: "to take a walk", kanji: "散歩します" },
  { japanese: "たいへん", english: "hard, rough, awful", kanji: "大変" },
  { japanese: "ほしい", english: "want (something)", kanji: "欲しい" },
  { japanese: "さびしい", english: "lonely", kanji: "寂しい" },
  { japanese: "ひろい", english: "spacious", kanji: "広い" },
  { japanese: "せまい", english: "narrow, small (e.g. room)", kanji: "狭い" },
  { japanese: "しやくしょ", english: "municipality", kanji: "市役所" },
  { japanese: "プール", english: "swimming pool", kanji: "" },
  { japanese: "かわ", english: "river", kanji: "川" },
  { japanese: "けいざい", english: "economy, economics", kanji: "経済" },
  { japanese: "びじゅつ", english: "fine arts", kanji: "美術" },
  { japanese: "つり", english: "fishing", kanji: "釣り" },
  { japanese: "つりをします", english: "to fish", kanji: "釣りをします" },
  { japanese: "スキー", english: "skiing", kanji: "" },
  { japanese: "スキーをします", english: "to ski", kanji: "" },
  { japanese: "かいぎ", english: "meeting, conference", kanji: "会議" },
  { japanese: "とうろく", english: "registration", kanji: "登録" },
  { japanese: "しゅうまつ", english: "weekend", kanji: "週末" },
  { japanese: "なにか", english: "something", kanji: "何か" },
  { japanese: "どこか", english: "somewhere, some place", kanji: "" },
  { japanese: "ごちゅうもんは?", english: "may I take your order?", kanji: "" },
  { japanese: "ていしょく", english: "set meal", kanji: "定食" },
  { japanese: "べつべつ「に」", english: "separately, individually", kanji: "別々に" },
  { japanese: "おなかが すきました", english: "(I’m) hungry; lit. “stomach is hungry”", kanji: "" },
  { japanese: "おなかが いっぱいです", english: "(I’m) full; lit. “stomach is full”", kanji: "" },
  { japanese: "のどが かわきました", english: "(I’m) thirsty; lit. “throat is dry”", kanji: "" },
  { japanese: "そう しましょう", english: "Let’s do that (used when agreeing with someone’s suggestion)", kanji: "" },
  { japanese: "つけます", english: "to turn on", kanji: "" },
  { japanese: "けします", english: "to turn off", kanji: "消します" },
  { japanese: "あけます", english: "to open", kanji: "開けます" },
  { japanese: "しめます", english: "to close", kanji: "閉めます" },
  { japanese: "いそぎます", english: "to hurry", kanji: "急ぎます" },
  { japanese: "まちます", english: "to wait", kanji: "待ちます" },
  { japanese: "とめます", english: "to stop, to park", kanji: "止めます" },
  { japanese: "みぎへまがります", english: "to turn to the right", kanji: "右へ曲がります" },
  { japanese: "もちます", english: "to hold", kanji: "持ちます" },
  { japanese: "てつだいます", english: "to help (with a task)", kanji: "手伝います" },
  { japanese: "よびます", english: "to call", kanji: "呼びます" },
  { japanese: "はなします", english: "to speak, to talk", kanji: "" },
  { japanese: "みせます", english: "to show", kanji: "見せます" },
  { japanese: "はじめます", english: "to begin", kanji: "始めます" },
  { japanese: "エアコン", english: "air conditioner", kanji: "" },
  { japanese: "パスポート", english: "passport", kanji: "" },
  { japanese: "なまえ", english: "name", kanji: "名前" },
  { japanese: "じゅうしょ", english: "address", kanji: "住所" },
  { japanese: "ちず", english: "map", kanji: "地図" },
  { japanese: "しお", english: "salt", kanji: "塩" },
  { japanese: "さとう", english: "sugar", kanji: "砂糖" },
  { japanese: "よみかた", english: "how to read, way of reading", kanji: "読み方" },
  { japanese: "ゆっくり", english: "slowly, leisurely", kanji: "" },
  { japanese: "すぐ", english: "immediately", kanji: "" },
  { japanese: "あと「で」", english: "later", kanji: "" },
  { japanese: "さあ", english: "right! (used when encouraging some course of action)", kanji: "" },
  { japanese: "あれ?", english: "Oh? (surprised)", kanji: "" },
  { japanese: "まっすぐ", english: "straight (ahead)", kanji: "" },
  { japanese: "おつり", english: "change (as in money), balance due", kanji: "お釣り" },
  { japanese: "たちます", english: "to stand up", kanji: "立ちます" },
  { japanese: "すわります", english: "to sit down", kanji: "座ります" },
  { japanese: "つかいます", english: "to use", kanji: "使います" },
  { japanese: "つくります", english: "to make, to produce", kanji: "作ります or 造ります" },
  { japanese: "うります", english: "to sell", kanji: "売ります" },
  { japanese: "しります", english: "to know", kanji: "知ります" },
  { japanese: "けんきゅうします", english: "to research", kanji: "研究します" },
  { japanese: "すんでいます", english: "to live (at)", kanji: "住んでいます" },
  { japanese: "しりょう", english: "data, document(s)", kanji: "資料" },
  { japanese: "カタログ", english: "catalog", kanji: "" },
  { japanese: "じこくひょう", english: "timetable", kanji: "時刻表" },
  { japanese: "ふく", english: "clothes", kanji: "服" },
  { japanese: "せいひん", english: "products, manufactured goods", kanji: "製品" },
  { japanese: "ソフト", english: "software", kanji: "" },
  { japanese: "せんもん", english: "speciality, field of study", kanji: "専門" },
  { japanese: "とこや", english: "barbershop", kanji: "床屋" },
  { japanese: "どくしん", english: "single, not married", kanji: "独身" },
  { japanese: "とく「に」", english: "especially", kanji: "特「に」" },
  { japanese: "ようちえん", english: "kindergarten", kanji: "幼稚園" },
  { japanese: "しょうがっこう", english: "elementary school", kanji: "小学校" },
  { japanese: "ちゅうがっこう", english: "junior high school", kanji: "中学校" },
  { japanese: "こうとうがっこう", english: "senior high school", kanji: "高等学校" },
  { japanese: "はいしゃ", english: "dentist", kanji: "歯医者" },
  { japanese: "のります", english: "to ride, to get on (trains, etc.)", kanji: "乗ります" },
  { japanese: "おります", english: "to get off (trains, etc.)", kanji: "降ります" },
  { japanese: "のりかえます", english: "to change (trains, etc.)", kanji: "乗り換えます" },
  { japanese: "あびます", english: "to bathe", kanji: "浴びます" },
  { japanese: "いれます", english: "to put in, to insert", kanji: "入れます" },
  { japanese: "だします", english: "to take out, to withdraw", kanji: "出します" },
  { japanese: "おします", english: "to push, to press", kanji: "押します" },
  { japanese: "わかい", english: "young", kanji: "若い" },
  { japanese: "ながい", english: "long", kanji: "長い" },
  { japanese: "みじかい", english: "short", kanji: "短い" },
  { japanese: "あかるい", english: "bright, light", kanji: "明るい" },
  { japanese: "くらい", english: "dark", kanji: "暗い" },
  { japanese: "からだ", english: "body", kanji: "体" },
  { japanese: "あたま", english: "head", kanji: "頭" },
  { japanese: "かお", english: "face", kanji: "顔" },
  { japanese: "め", english: "eye", kanji: "目" },
  { japanese: "みみ", english: "ear", kanji: "耳" },
  { japanese: "くち", english: "mouth", kanji: "口" },
  { japanese: "は", english: "tooth", kanji: "歯" },
  { japanese: "おなか", english: "stomach", kanji: "" },
  { japanese: "あし", english: "leg, foot", kanji: "足" },
  { japanese: "サービス", english: "service", kanji: "" },
  { japanese: "ジョギング", english: "jogging", kanji: "" },
  { japanese: "シャワー", english: "shower", kanji: "" },
  { japanese: "みどり", english: "green", kanji: "緑" },
  { japanese: "てら", english: "Buddhist temple", kanji: "寺" },
  { japanese: "じんじゃ", english: "Shinto shrine", kanji: "神社" },
  { japanese: "りゅうがくせい", english: "foreign student", kanji: "留学生" },
  { japanese: "どうやって", english: "in what way, how", kanji: "" },
  { japanese: "まず", english: "first of all", kanji: "" },
  { japanese: "あんしょうばんごう", english: "personal identification number (PIN)", kanji: "暗証番号" },
  { japanese: "つぎに", english: "next, as a next step", kanji: "次に" },
  { japanese: "きんがく", english: "amount of money", kanji: "金額" },
  { japanese: "かくにん", english: "confirmation", kanji: "確認" },
  { japanese: "アジア", english: "Asia", kanji: "" },
  { japanese: "おぼえます", english: "to remember", kanji: "覚えます" },
  { japanese: "わすれます", english: "to forget", kanji: "忘れます" },
  { japanese: "なくします", english: "to lose (something)", kanji: "" },
  { japanese: "はらいます", english: "to pay", kanji: "払います" },
  { japanese: "かえします", english: "to give back, to return", kanji: "返します" },
  { japanese: "ぬぎます", english: "to take off (clothes, shoes, etc.)", kanji: "脱ぎます" },
  { japanese: "もっていきます", english: "to take (something)", kanji: "持って行きます" },
  { japanese: "もってきます", english: "to bring (something)", kanji: "持ってきます" },
  { japanese: "しんぱいします", english: "to worry", kanji: "心配します" },
  { japanese: "ふろ", english: "bath", kanji: "" },
  { japanese: "たいせつ", english: "important, precious", kanji: "大切" },
  { japanese: "だいじょうぶ", english: "all right, it’s ok", kanji: "大丈夫" },
  { japanese: "あぶない", english: "dangerous", kanji: "危ない" },
  { japanese: "もんだい", english: "question, problem", kanji: "問題" },
  { japanese: "こたえ", english: "answer, response", kanji: "答え" },
  { japanese: "きんえん", english: "non-smoking", kanji: "禁煙" },
  { japanese: "けんこう", english: "health", kanji: "健康" },
  { japanese: "かぜ", english: "cold, flu", kanji: "" },
  { japanese: "ねつ", english: "fever", kanji: "熱" },
  { japanese: "びょうき", english: "illness", kanji: "病気" },
  { japanese: "くすり", english: "medicine", kanji: "薬" },
  { japanese: "うわぎ", english: "jacket, outerwear", kanji: "上着" },
  { japanese: "したぎ", english: "underwear", kanji: "下着" },
  { japanese: "のど", english: "throat", kanji: "" },
  { japanese: "おだいじに", english: "take care of yourself (said to people who are ill)", kanji: "お大事に" },
  { japanese: "できます", english: "to be able to", kanji: "" },
  { japanese: "あらいます", english: "to wash", kanji: "洗います" },
  { japanese: "ひきます", english: "to pull", kanji: "引きます" },
  { japanese: "うたいます", english: "to sing", kanji: "歌います" },
  { japanese: "あつめます", english: "to collect, to gather", kanji: "集めます" },
  { japanese: "すてます", english: "to throw away", kanji: "捨てます" },
  { japanese: "かえます", english: "to exchange, to change", kanji: "換えます" },
  { japanese: "うんてんします", english: "to drive", kanji: "運転します" },
  { japanese: "よやくします", english: "to reserve, to book", kanji: "予約します" },
  { japanese: "けんがくします", english: "to visit some place for study, to study by observation (field trip)", kanji: "見学します" },
  { japanese: "ピアノ", english: "piano", kanji: "" },
  { japanese: "げんきん", english: "cash", kanji: "現金" },
  { japanese: "しゅみ", english: "hobby", kanji: "趣味" },
  { japanese: "にっき", english: "diary", kanji: "日記" },
  { japanese: "いのり", english: "prayer", kanji: "祈り" },
  { japanese: "かちょう", english: "section chief", kanji: "課長" },
  { japanese: "ぶちょう", english: "department chief", kanji: "部長" },
  { japanese: "しゃちょう", english: "president of a company", kanji: "社長" },
  { japanese: "どうぶつ", english: "animal", kanji: "動物" },
  { japanese: "うま", english: "horse", kanji: "馬" },
  { japanese: "なかなか", english: "not easily (used with negatives)", kanji: "" },
  { japanese: "ぼくじょう", english: "ranch, stock farm", kanji: "牧場" },
  { japanese: "ぜひ", english: "by all means", kanji: "" },
  { japanese: "やまにのぼります", english: "to climb a mountain", kanji: "山に登ります" },
  { japanese: "とまります", english: "to stay (at a place, e.g. a hotel)", kanji: "泊ります" },
  { japanese: "そうじします", english: "to clean (a room)", kanji: "掃除します" },
  { japanese: "せんたくします", english: "to wash (clothes)", kanji: "洗濯します" },
  { japanese: "れんしゅうします", english: "to practice", kanji: "練習します" },
  { japanese: "ねむい", english: "sleepy", kanji: "眠い" },
  { japanese: "つよい", english: "strong", kanji: "強い" },
  { japanese: "よわい", english: "weak (strength)", kanji: "弱い" },
  { japanese: "ちょうし", english: "condition", kanji: "調子" },
  { japanese: "ゴルフ", english: "golf", kanji: "" },
  { japanese: "すもう", english: "sumo wrestling", kanji: "相撲" },
  { japanese: "パチンコ", english: "pachinko (some kind of pinball game)", kanji: "" },
  { japanese: "ひ", english: "day, date", kanji: "日" },
  { japanese: "いちど", english: "once", kanji: "一度" },
  { japanese: "いちども", english: "never, not once (used with negatives)", kanji: "一度も" },
  { japanese: "だんだん", english: "gradually", kanji: "" },
  { japanese: "もうすぐ", english: "soon", kanji: "" },
  { japanese: "おかげさまで", english: "thank you (used when expressing gratitude for help received)", kanji: "" },
  { japanese: "かんぱい", english: "cheers(!), bottoms up(!)", kanji: "乾杯" },
  { japanese: "じつは", english: "actually, to tell the truth", kanji: "実は" },
  { japanese: "ダイエット", english: "diet", kanji: "" },
  { japanese: "ダイエットをします", english: "to go on a diet", kanji: "" },
  { japanese: "しかし", english: "however, but", kanji: "" },
  { japanese: "むり", english: "excessive, impossible", kanji: "無理" },
  { japanese: "ケーキ", english: "cake", kanji: "" },
  { japanese: "ビザがいります", english: "to need/require a visa", kanji: "ビザが要ります" },
  { japanese: "しらべます", english: "to check, to investigate", kanji: "調べます" },
  { japanese: "なおします", english: "to repair, to correct", kanji: "直します" },
  { japanese: "しゅうりします", english: "to repair", kanji: "修理します" },
  { japanese: "でんわします", english: "to phone", kanji: "電話します" },
  { japanese: "ぼく", english: "I (me) (an informal equivalent of わたし used by men)", kanji: "僕" },
  { japanese: "きみ", english: "you (an informal equivalent of あなた used by men)", kanji: "君" },
  { japanese: "サラリーマン", english: "salaried worker, office worker", kanji: "" },
  { japanese: "ことば", english: "word(s)", kanji: "" },
  { japanese: "ぶっか", english: "commodity prices", kanji: "物価" },
  { japanese: "きもの", english: "kimono (traditional Japanese attire)", kanji: "着物" },
  { japanese: "はじめ", english: "the beginning", kanji: "初め" },
  { japanese: "おわり", english: "the end", kanji: "終わり" },
  { japanese: "こっち", english: "this place/way/direction (close to speaker) [informal]", kanji: "" },
  { japanese: "そっち", english: "that place/way/direction (distant from speaker, close to listener) [informal]", kanji: "" },
  { japanese: "あっち", english: "that place/way/direction (distant from both speaker and listener) [informal]", kanji: "" },
  { japanese: "どっち", english: "which one (between two things), which way, where [informal]", kanji: "" },
  { japanese: "このあいだ", english: "the other day", kanji: "この間" },
  { japanese: "みんな「で」", english: "all together (everybody)", kanji: "" },
  { japanese: "よかったら", english: "if you like", kanji: "" },
  { japanese: "おもいます", english: "to think", kanji: "思います" },
  { japanese: "いいます", english: "to say", kanji: "言います" },
  { japanese: "たります", english: "to be enough, to be sufficient", kanji: "足ります" },
  { japanese: "かちます", english: "to win", kanji: "勝ちます" },
  { japanese: "まけます", english: "to lose (be beaten)", kanji: "負けます" },
  { japanese: "おまつりがあります", english: "a festival to take place", kanji: "お祭りがあります" },
  { japanese: "むだ", english: "futility", kanji: "" },
  { japanese: "ふべん", english: "inconvenient", kanji: "不便" },
  { japanese: "おなじ", english: "the same", kanji: "同じ" },
  { japanese: "すごい", english: "great! (expresses astonishment or admiration)", kanji: "" },
  { japanese: "しゅしょう", english: "prime minister", kanji: "首相" },
  { japanese: "だいとうりょう", english: "president", kanji: "大統領" },
  { japanese: "せいじ", english: "politics", kanji: "政治" },
  { japanese: "ニュース", english: "news", kanji: "" },
  { japanese: "スピーチ", english: "speech", kanji: "" },
  { japanese: "しあい", english: "game, match", kanji: "" },
  { japanese: "アルバイト", english: "side job", kanji: "" },
  { japanese: "いけん", english: "opinion", kanji: "意見" },
  { japanese: "はなし", english: "talk, speech, story", kanji: "話" },
  { japanese: "ユーモア", english: "humour", kanji: "" },
  { japanese: "デザイン", english: "design", kanji: "" },
  { japanese: "こうつう", english: "transportation, traffic", kanji: "交通" },
  { japanese: "ラッシュ", english: "rush hour", kanji: "" },
  { japanese: "さいきん", english: "recently, these days", kanji: "最近" },
  { japanese: "たぶん", english: "probably", kanji: "" },
  { japanese: "きっと", english: "surely", kanji: "" },
  { japanese: "ほんとう「に」", english: "really", kanji: "" },
  { japanese: "そんな「に」", english: "not so much (used with negatives)", kanji: "" },
  { japanese: "しばらくですね", english: "long time no see", kanji: "" },
  { japanese: "もちろん", english: "of course", kanji: "" },
  { japanese: "はきます", english: "to put on, to wear (trousers, shoes, etc. [lower body + footwear] )", kanji: "" },
  { japanese: "かぶります", english: "to put on, to wear (hat, etc. [on head] )", kanji: "" },
  { japanese: "めがねをかけます", english: "to put on glasses", kanji: "眼鏡をかけます" },
  { japanese: "うまれます", english: "to be born", kanji: "生まれます" },
  { japanese: "コート", english: "coat", kanji: "" },
  { japanese: "スーツ", english: "suit", kanji: "" },
  { japanese: "セーター", english: "sweater", kanji: "" },
  { japanese: "ぼうし", english: "hat, cap", kanji: "帽子" },
  { japanese: "めがね", english: "glasses", kanji: "眼鏡" },
  { japanese: "おめでとう", english: "congratulations", kanji: "" },
  { japanese: "やちん", english: "house rent", kanji: "家賃" },
  { japanese: "わしつ", english: "Japanese-style room", kanji: "和室" },
  { japanese: "おしいれ", english: "Japanese-style closet", kanji: "押し入れ" },
  { japanese: "ふとん", english: "Japanese-style mattress and quilt", kanji: "布団" },
  { japanese: "アパート", english: "apartment", kanji: "" },
  { japanese: "まわします", english: "to turn", kanji: "回します" },
  { japanese: "さわります", english: "to touch, to feel", kanji: "触ります" },
  { japanese: "うごきます", english: "to move (motion), to stir, to shake", kanji: "動きます" },
  { japanese: "あるきます", english: "to walk", kanji: "歩きます" },
  { japanese: "わたります", english: "to cross over, to go across", kanji: "渡ります" },
  { japanese: "ひっこしします", english: "to move (to a different house)", kanji: "引っ越しします" },
  { japanese: "でんきや", english: "electrician", kanji: "電気屋" },
  { japanese: "サイズ", english: "size", kanji: "" },
  { japanese: "おと", english: "sound", kanji: "音" },
  { japanese: "きかい", english: "machine", kanji: "機械" },
  { japanese: "つまみ", english: "knob, handle", kanji: "" },
  { japanese: "こしょう", english: "breakdown", kanji: "故障" },
  { japanese: "みち", english: "road, way", kanji: "道" },
  { japanese: "こうさてん", english: "crossing", kanji: "交差点" },
  { japanese: "しんごう", english: "traffic light", kanji: "信号" },
  { japanese: "かど", english: "corner", kanji: "角" },
  { japanese: "ちゅうしゃじょう", english: "parking lot", kanji: "駐車場" },
  { japanese: "しょうがつ", english: "New Year’s Day", kanji: "正月" },
  { japanese: "たてもの", english: "building", kanji: "建物" },
  { japanese: "くれます", english: "to give (me), to be given", kanji: "" },
  { japanese: "つれていきます", english: "to take along (someone)", kanji: "連れて行きます" },
  { japanese: "つれてきます", english: "to bring along (someone)", kanji: "連れてきます" },
  { japanese: "しょうかいします", english: "to introduce", kanji: "紹介します" },
  { japanese: "あんないします", english: "to show around, to show the way", kanji: "案内します" },
  { japanese: "せつめいします", english: "to explain", kanji: "説明します" },
  { japanese: "コーヒーをいれます", english: "to make coffee", kanji: "" },
  { japanese: "おじいさん", english: "grandfather", kanji: "" },
  { japanese: "おじいちゃん", english: "old man", kanji: "" },
  { japanese: "おばあさん", english: "grandmother", kanji: "" },
  { japanese: "おばあちゃん", english: "old woman", kanji: "" },
  { japanese: "じゅんび", english: "preparation", kanji: "準備" },
  { japanese: "いみ", english: "meaning", kanji: "意味" },
  { japanese: "かし", english: "sweets, snacks", kanji: "菓子" },
  { japanese: "じぶん「で」", english: "(by) oneself", kanji: "自分「で」" },
  { japanese: "ほか「に」", english: "besides", kanji: "" },
  { japanese: "べんとう", english: "lunch box", kanji: "弁当" },
  { japanese: "ははのひ", english: "Mother’s day", kanji: "母の日" },
  { japanese: "ちちのひ", english: "Father&#x27;s day", kanji: "父の日" },
  { japanese: "かんがえます", english: "to reconsider, to think", kanji: "考えます" },
  { japanese: "つきます", english: "to arrive", kanji: "着きます" },
  { japanese: "りゅうがくします", english: "to study abroad", kanji: "留学します" },
  { japanese: "いなか", english: "countryside, hometown", kanji: "田舎" },
  { japanese: "たいしかん", english: "embassy", kanji: "大使館" },
  { japanese: "グループ", english: "group", kanji: "" },
  { japanese: "チャンス", english: "chance", kanji: "" },
  { japanese: "おく", english: "hundred million", kanji: "億" },
  { japanese: "てんきん", english: "(job) transfer", kanji: "転勤" },
  { japanese: "こと", english: "thing, matter", kanji: "" },
  { japanese: "がんばります", english: "to do one’s best", kanji: "頑張ります" },
];
